-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 15:36:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoservis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autoservis` ;

-- -----------------------------------------------------
-- Schema autoservis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoservis` DEFAULT CHARACTER SET utf8 ;
USE `autoservis` ;

-- -----------------------------------------------------
-- Table `autoservis`.`zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoservis`.`zamestnanci` ;

CREATE TABLE IF NOT EXISTS `autoservis`.`zamestnanci` (
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `osobnicislo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`osobnicislo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservis`.`automobily`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoservis`.`automobily` ;

CREATE TABLE IF NOT EXISTS `autoservis`.`automobily` (
  `idautomobily` INT NOT NULL AUTO_INCREMENT,
  `registracni_znacka` VARCHAR(45) NOT NULL,
  `vyrobce` VARCHAR(45) NOT NULL,
  `typ_vozu` VARCHAR(45) NOT NULL,
  `rok_vyroby` INT NOT NULL,
  `obsah_motoru` INT NOT NULL,
  `prevodovka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idautomobily`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservis`.`majitele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoservis`.`majitele` ;

CREATE TABLE IF NOT EXISTS `autoservis`.`majitele` (
  `idmajitele` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `automobily_idautomobily` INT NOT NULL,
  PRIMARY KEY (`idmajitele`, `automobily_idautomobily`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservis`.`nahradni_dily`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoservis`.`nahradni_dily` ;

CREATE TABLE IF NOT EXISTS `autoservis`.`nahradni_dily` (
  `iddilu` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `cena` VARCHAR(45) NOT NULL,
  `sklad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddilu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoservis`.`opravy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoservis`.`opravy` ;

CREATE TABLE IF NOT EXISTS `autoservis`.`opravy` (
  `automobily_idautomobily` INT NULL,
  `nahradni_dily_iddilu` INT NULL,
  `zamestananci_osobnicislo` INT NULL,
  PRIMARY KEY (`automobily_idautomobily`, `nahradni_dily_iddilu`, `zamestananci_osobnicislo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
